
                	
                    	
                        <div class="title1"> 
                        <div style="padding-top:11px; padding-left:65px"><span style="padding-top:10px;">YOUR CART</span></div>
                        </div>
                      <form name="your-cart" id="your-cart" action="" method="POST">  
                 <?php 
                 $count= (count($this->cart));
              
                    if ($count !=0){
                 ?>
                     <div class="sanpham">
                     	
                            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                        <thead>
                                    <tr>
                                    <th >ID</th>

                                    <th >Tiêu đề</th>
                                    <th >Số lượng</th>
                                    <th >Giá bán</th>
                                    <th >Tổng tiền </th>
                                   
                                    </tr>
                        </thead>
                     	
                       
                        	
                            <?php 
//                            echo '<pre>';
//                            print_r($this->cart);
//                            echo '</pre>';
                           // echo ($this->cart[0]);
                            
                             
                            $cart = $this->cart;
                           
                             
                           
                            
                                //echo $cart[$i];
                            	if(count($this->Items)>0){
                            		$totalPrice = 0;
                            		foreach ($this->Items as  $val){
                            			$name = $val['title'];
                            			$id = $val['id'];
                            			$price = $val['price'];
                            			 $quantity = $cart[$id];
                                                
                            			$total = 0;
                                                
                                                 
                                            $price=number_format($price, 0 , '.', '.');
	                            		
                                            //$price = '<span class="price-1" style="text-decoration: line-through;">$' . $price . '</span> ';

                                             $total = $quantity * $val['price']; 
                                             $totalPrice += $total; 
                                            
                                            $total = number_format($total, 0 , '.', '.');		 
		                          		
		                          	
		                          		
									  
//		                          		$linkDetial = $this->baseUrl('/shopping/index/detail/cid/' . $val['cat_id'] 
//	                          									 . '/tcat/' . $val['category_name'] 
//	                          									 . '/id/' . $val['id'] . '/title/' . $filter->filter($val['name']));

	                          		    $itemProduct = 'itemProduct[' . $val['id'] . ']';				 
                            			$itemProduct = $this->formText($itemProduct,$quantity,
                            											array('style'=>'width: 35px; text-align: center; font-size: 11px; background-color:#FFC;'));

                            			$linkOrder = $this->baseUrl('/shopping/index/order');
                            			$linkBack = $this->baseUrl('/shoppingcart');
                                                $linkupdate = $this->baseUrl('/shopping/index/order');
                            ?>
                        <tr>
                            <td><?php echo $id;?></td>
                            <td><a href="<?php //echo $linkDetial;?>" class="itemLink" target="_blank"><?php echo $name;?></a></td>
                            <td><?php echo $itemProduct;?> </td>
                            <td><?php echo $price;?></td>
                            <td><?php echo $total;?></td>
                        </tr>
              			
                         	<?php 
                            		
                                } }
                         	?>   
                            
                        <tr>
                            <td colspan="4" style="text-align: right;" >Tổng số tiền bạn phải trả là:</td>
                            <td><?php 
                            $totalPrice =number_format($totalPrice, 0 , '.', '.');
                            echo  $totalPrice;?>  </td>
                        </tr>  
                            </table>
                        <div class="clear"></div>
                           
                                          	
                        <div class="cartDetail-button">
                        	<input type="button" name="update" id="update" value="&laquo; Tiếp tục mua hàng" class="btn btn-primary" /> 
                        	<input type="submit" name="update" id="load" value="Cập nhật giỏ hàng" class="btn btn-primary"  /> 
                                <input type="button" name="update" id="order" value="Gửi thanh toán &raquo;" class="btn btn-primary" /> 
                            
                        </div>
                      
 <div class="row-fluid sortable" id="order_detail" > 
      <div>
    <div class="box-content">  
        <div class="control-group">
                  <label class="control-label" for="typeahead">Tên đầy đủ</label>
                  <div class="controls">
                    <input name="fullname" type="text" class="span6 typeahead" id="fullname"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    <div class="warning" id="full_nameError">Vui lòng nhập tên của bạn</div>
               
                  </div>
	</div>
                        
                        
                        
                      
      <div class="control-group">
                  <label class="control-label" for="typeahead">Địa chỉ </label>
                  <div class="controls">
                    <input name="address" type="text" class="span6 typeahead" id="address"  data-provide="typeahead" data-items="4" >
                     <div class="warning" id="addressError">Vui lòng nhập địa chỉ của bạn</div>
               
                  </div>
	</div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Email</label>
                  <div class="controls">
                    <input name="email" type="text" class="span6 typeahead" id="email"  data-provide="typeahead" data-items="4" >
                    <div class="warning" id="emailError">Vui lòng nhập đúng định dạng email của bạn</div>
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Điện thoại</label>
                  <div class="controls">
                    <input name="phone" type="text" class="span6 typeahead" id="phone"  data-provide="typeahead" >
                     <div class="warning" id="phoneError">Vui lòng nhập đúng định dạng của bạn</div>
               
                  </div>
    </div>
    <div class="control-group">
                  <label class="control-label" for="typeahead">Nội dung</label>
                  <div class="controls">
                    <textarea name="coment" cols="70" rows="10" class="span6 typeahead" id="typeahead" ></textarea>
                    
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Captcha </label>
                  <div class="controls">
                      <label><?php echo $this->captcha; ?></label>
                    
                    
                      <input name="captcha" type="text" class="span6 typeahead" id="captcha"  placeholder="Nhập ký tự ở trên" >
                    <?php echo $this->formHidden('captcha_id',$this->captchaID)?>
                <div class="warning" id="captchaError">Vui lòng nhập captcha</div>
                  </div>
    </div>
    
      <div class="form-actions">
          <button type="submit" class="btn btn-primary" id="Send">Gửi thanh toán</button>
                  <button type="reset" class="btn">Cancel</button>
     </div>
</div></div></div>
                        
                        </form> 
                  </div>
<?php } else { echo "Bạn chưa mua hàng"; } ?>
<script>
     $( "#update" ).click(function() {
            
//            $( ".sanpham" ).load( "ajax/test.html" );
        window.location.href='<?= $this->baseUrl() ?>';
  
        });

    
        $( "#load" ).click(function() {
            
//            $( ".sanpham" ).load( "ajax/test.html" );
            window.location.href='<?= $this->baseUrl() ?>/shoppingcart';
        });


    
        $( "#order" ).click(function() {
  $( "#order_detail" ).show( "slow", function() {
    // Animation complete.
  });
});






$('body').bind('mousewheel DOMMouseScroll', function(e) {
    var scrollTo = null;

    if (e.type == 'mousewheel') {
        scrollTo = (e.originalEvent.wheelDelta * -1);
    }
    else if (e.type == 'DOMMouseScroll') {
        scrollTo = 40 * e.originalEvent.detail;
    }

    if (scrollTo) {
        e.preventDefault();
        $(this).scrollTop(scrollTo + $(this).scrollTop());
    }
});
</script>    

<script type="text/javascript" src="<?php echo $this->baseurl();  ?>/js/AJAX_4.js"></script>