<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/user/adduser/">Thêm user</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/user/listuser/">Danh sách user</a> 
        </li>
</ul>
</div>




<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">

<?php
foreach ($this->books as $val)
{

   
 
    ?>
   
  
 
    
<form action='' method='post' enctype='multipart/form-data' name='tt_mh' id='tt_mh'class="form-horizontal"  >
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Tên đầy đủ </label>
                  <div class="controls">
                      <input name="full_name" value="<?php  echo $this->escape($val['full_name']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
    </div>
    
    
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Username </label>
                  <div class="controls">
                    <input name="username" value="<?php  echo $this->escape($val['username']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Password </label>
                  <div class="controls">
                    <input name="password" type="password" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Nhập lại Password </label>
                  <div class="controls">
                    <input name="re_password" type="password" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
    </div>
    
    <input type="hidden" name="pass_hidden" value="<?php  echo $this->escape($val['password']); ?>">
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Email </label>
                  <div class="controls">
                    <input name="email" type="text" value="<?php  echo $this->escape($val['email']); ?>" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
    </div>
    
    
    
    
    
    <div class="control-group">
            <label class="control-label">Trạng thái</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="status" id="optionsRadios1" value="1" <?php if ($val['status']==1){    echo 'checked';} ?>>
                    Bật
              </label>
              
              <label class="radio">
                    <input type="radio" name="status" id="optionsRadios2" value="0"<?php if ($val['status']==0){    echo 'checked';} ?>>
                   Không
              </label>
            </div>
	</div>
    
    <div class="control-group">
            <label class="control-label">Thuộc nhóm</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="group_name" id="optionsRadios2" value="" <?php if ($val['group_name']==''){    echo 'checked';} ?> >
                    Admin &nbsp;&nbsp;&nbsp;
              </label>
              
              <label class="radio">
                    <input type="radio" name="group_name" id="optionsRadios2" value="1" <?php if ($val['group_name']==1){    echo 'checked';} ?>>
                   Seller &nbsp;&nbsp;&nbsp;
              </label>
              
              <label class="radio">
                    <input type="radio" name="group_name" id="optionsRadios2" value="2" <?php if ($val['group_name']==2){    echo 'checked';} ?>>
                   User &nbsp;&nbsp;&nbsp;
              </label>
              <label class="radio">
                    <input type="radio" name="group_name" id="optionsRadios2" value="3" <?php if ($val['group_name']==3){    echo 'checked';} ?>>
                   Amo &nbsp;&nbsp;&nbsp;
              </label>
            </div>
	</div>
    
    
        <div class="form-actions">
                  <button type="submit" class="btn btn-primary">Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
    
          
    
      </form>
<?php
    }
?>
    </div></div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/user/adduser/">Thêm user</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/user/listuser/">Danh sách user</a> 
        </li>
</ul>
</div>