<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/addsupport/">Thêm hổ trợ tực tuyến</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/listsupport/">Danh sách hổ trợ tực tuyến</a> 
        </li>
</ul>
</div>




<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">

<?php
foreach ($this->books as $val)
{

   
 
    ?>
   
  
 
    
<form action='' method='post' enctype='multipart/form-data' name='tt_mh' id='tt_mh'class="form-horizontal"  >
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Tên nick </label>
                  <div class="controls">
                      <input name="nickname" value="<?php  echo $this->escape($val['nickname']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Loại nick </label>
                  <div class="controls">
              <label class="radio">
                    <input type="radio" name="loai_nick" id="optionsRadios1" value="yahoo" <?php if ($val['loai_nick']=='yahoo'){    echo 'checked';} ?>>
                    Yahoo
              </label>
              <div style="clear:both"></div>
              <label class="radio">
                    <input type="radio" name="loai_nick" id="optionsRadios2" value="skype"<?php if ($val['loai_nick']=='skype'){    echo 'checked';} ?>>
                   Skype
              </label>
            </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Tên đại diện </label>
                  <div class="controls">
                    <input name="name" value="<?php  echo $this->escape($val['name']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Hotline </label>
                  <div class="controls">
                    <input name="hotline" type="text" value="<?php  echo $this->escape($val['hotline']); ?>" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
    </div>
    
    
    
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Vị trí </label>
                  <div class="controls">
                    <input name="position" value="<?php  echo $this->escape($val['position']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    <div class="control-group">
            <label class="control-label">Hiển thị</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="active" id="optionsRadios1" value="1" <?php if ($val['active']==1){    echo 'checked';} ?>>
                    Có
              </label>
              <div style="clear:both"></div>
              <label class="radio">
                    <input type="radio" name="active" id="optionsRadios2" value="2"<?php if ($val['active']==2){    echo 'checked';} ?>>
                   Không
              </label>
            </div>
	</div>
    
    
        <div class="form-actions">
                  <button type="submit" class="btn btn-primary">Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
    
          
    
      </form>
<?php
    }
?>
    </div></div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/addsupport/">Thêm hổ trợ tực tuyến</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/listsupport/">Danh sách hổ trợ tực tuyến</a> 
        </li>
</ul>
</div>