<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/addsupport/">Thêm hổ trợ tực tuyến</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/listsupport/">Danh sách hổ trợ tực tuyến</a> 
        </li>
</ul>
</div>

<div class="row-fluid sortable">
<div class="box span12">
    
<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
   <div class="box-content"> 
<table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
    <tr><th >STT</th>
  
    <th>Tên đại diện</th>
   
    <th>Nickname</th>
     <th>Loại nick</th>
     <th>Hotline</th>
     <th>Vị trí</th>
    <th>Hiển thị</th>
    <th >Xóa</th>
    <th >Sửa</th>
  </tr>
  
    </thead>
  
      <?php
      $stt=1;
      $url=$this->baseUrl();
      foreach($this->books as $val)
        {
          $id=$val['id'];
          $edit=$this->url(array('action'=>'editsupport','id'=>$id));
          $del=$this->url(array('action'=>'deletesupport','id'=>$id));
          $update_active=$this->url(array('action'=>'useractive','id'=>$id,'active'=>0));
          $update_inactive=$this->url(array('action'=>'useractive','id'=>$id,'active'=>1));
         
           $status=$val['active'];
          if($status==1){$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" >Active</a>  <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\" style='display:none'>Inactive</a>";}
          else {$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" style='display:none' >Active</a> <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\">Inactive</a>";}
           
          ?>
    <tr id="row_<?= $id ?>">
      <td ><?php echo $stt;?></td>
   <?php  echo "<td align='center'>".$val['name']."</td>"; ?>
      <td> <?php echo $val['nickname']; ?></td>
      
      <td> <?php echo $val['loai_nick']; ?></td>
      <td> <?php echo $val['hotline']; ?></td>

    <td> <?php echo $val['position']; ?></td>
    <td id="demo_active_<?= $id ?>">  <?php echo $tt; ?> </td>
 
   <td>
    
        <a class="btn btn-danger"  id="row_del_<?= $id ?>" href='#' >
	<i class="icon-trash icon-white"></i> 
	Delete
	</a>
    
    
    </td>
    <td ><a class="btn btn-info" href="<?php echo $edit;?>">
	<i class="icon-edit icon-white"></i>  
	Edit                                            
	</a>
    </td>
  </tr>
  <script>
            $( "#row_del_<?= $id ?>" ).live('click',function(event_ref) {  event_ref.preventDefault();
           if (confirm('Are you sure you wish to delete this record?')){
                $.post('<?= $del ?>');
                $( "#row_<?= $id ?>" ).hide(2000);
          }
    });
    
    
    $( "#active_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_active ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='inactive_<?= $id ?>' class=\"label\">Inactive</a>" );
              
         
    });
    
    $( "#inactive_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_inactive ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='active_<?= $id ?>' class=\"label label-success\">Active</a>" );
          
    });
</script>
  
  <?php $stt++;} ?>
  
 
  
  <tr ><td colspan="9">
          
      <?php 
      if($stt>=15) {
      echo $this->paginationControl($this->books,  'Sliding', 'page/pagination.phtml');}
      else {}
      ?>     
      </td>
  </tr>
    
</table>
   </div>
</div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
       <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/addsupport/">Thêm hổ trợ tực tuyến</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/support/listsupport/">Danh sách hổ trợ tực tuyến</a> 
        </li>
</ul>
</div>