<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/link/addlink/">Thêm link liên kết</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/link/listlink/">Danh sách link liên kết</a> 
        </li>
</ul>
</div>




<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">

<?php
foreach ($this->books as $val)
{

   
 
    ?>
   
  
 
    
<form action='' method='post' enctype='multipart/form-data' name='tt_mh' id='tt_mh'class="form-horizontal"  >
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Tiêu đề </label>
                  <div class="controls">
                      <input name="title" value="<?php  echo $this->escape($val['title']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
    </div>
    
   
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Link website</label>
                  <div class="controls">
                    <input name="link" value="<?php  echo $this->escape($val['link']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    <label>Chú link phải có http:// đầy đủ. Ví dụ như : http://google.vn/ </label>
               
                  </div>
    </div>
    
    
    
        <div class="form-actions">
                  <button type="submit" class="btn btn-primary">Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
    
          
    
      </form>
<?php
    }
?>
    </div></div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/link/addlink/">Thêm link liên kết</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/link/listlink/">Danh sách link liên kết</a> 
        </li>
</ul>
</div>