<div>
    <?= $this->render("video/menu.phtml") ?>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i> Members</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            <form action="" method="post" enctype="multipart/form-data" name="tt_mh" id="tt_mh"  class="form-horizontal">




                <div class="control-group">
                    <label class="control-label" for="typeahead">Tiêu đề </label>
                    <div class="controls">
                        <input name="title" required="" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >


                    </div>
                </div>


                <div class="control-group hidden">
                    <label class="control-label" for="fileInput">Hình ảnh</label>
                    <div class="controls">
                        <?php echo $this->formFile('images'); ?>
                    </div>
                </div>

                <div class="control-group hide">
                    <label class="control-label" for="typeahead">Mô tả </label>
                    <div class="controls">

                        <textarea name="description" cols="70" rows="10" class="span6 typeahead" id="typeahead" ></textarea>

                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="typeahead">Link </label>
                    <div class="controls">
                        <input required="" name="link" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >


                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="typeahead">Vị trí </label>
                    <div class="controls">
                        <input name="position" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4">


                    </div>
                </div>  
                <div class="control-group">
                    <label class="control-label">Hiển thị</label>
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="active" id="optionsRadios1" value="1" checked="">
                            Có
                        </label>
                        <div style="clear:both"></div>
                        <label class="radio">
                            <input type="radio" name="active" id="optionsRadios2" value="2">
                            Không
                        </label>
                    </div>
                </div>

                <div class="form-actions">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                    <button type="reset" class="btn">Cancel</button>
                </div>

            </form>
        </div>
    </div></div>
<div class="clear"></div>
<div>
    <?= $this->render("video/menu.phtml") ?>
</div>