<div>
    <?= $this->render("video/menu.phtml") ?>
</div>

<div class="row-fluid sortable">
    <div class="box span12">

        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i> Members</h2>
            <div class="box-icon">
                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
            </div>
        </div>
        <div class="box-content"> 
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr><th >STT</th>

                        <th>Tiêu đề</th>
                        <th>Hình ảnh</th> 

                        <th>Vị trí</th>



                        <th>Link</th>
                        <th>Active</th>
                        <th >Xóa</th>
                        <th >Sửa</th>
                    </tr>

                </thead>

                <?php
                $stt = 1;
                $url = $this->baseUrl();
                foreach ($this->books as $val) {
                    $id = $val['video_id'];
                    $edit = $this->url(array('action' => 'editvideo', 'id' => $id));
                    $del = $this->url(array('action' => 'deletevideo', 'id' => $id));
                    ?>
                    <tr id="row_<?= $id ?>">
                        <td ><?php echo $stt; ?> </td>
                        <?php echo "<td align='center'>" . $val['title'] . "</td>"; ?>
                        <td> 
                            <iframe width="180" height="80" src="<?php echo str_replace("watch?v=", "embed/", $val['link']); ?>" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
                        </td>

                        <td> <?php echo $val['position']; ?></td>
                        <td> <?php echo $val['link']; ?></td>

                        <td id="active_<?= $id ?>">
                            <?php if ($val['active'] == 1) { ?> 
                                <a href="javascript:void(0)" class="video_active" rel="1" id="<?= $id ?>">
                                    <span class="label label-success">Active</span>
                                </a>
                            <?php } else { ?>
                                <a href="javascript:void(0)" class="video_active" rel="2" id="<?= $id ?>"> 
                                    <span class="label">Inactive</span>
                                </a>
                            <?php } ?>
                        </td>


                        <td>

                            <a class="btn btn-danger"  id="row_del_<?= $id ?>" href='#' >
                                <i class="icon-trash icon-white"></i> 
                                Delete
                            </a>


                        </td>
                        <td ><a class="btn btn-info" href="<?php echo $edit; ?>">
                                <i class="icon-edit icon-white"></i>  
                                Edit                                            
                            </a>
                        </td>
                    </tr>
                    <script>
                        $("#row_del_<?= $id ?>").live('click', function (event_ref) {
                            event_ref.preventDefault();
                            if (confirm('Are you sure you wish to delete this record?')) {
                                $.post('<?= $del ?>');
                                $("#row_<?= $id ?>").hide(2000);
                            }
                        });
                    </script>
                    <?php
                    $stt++;
                }
                ?>



                <tr ><td colspan="9">

                        <?php
                        if ($stt >= 15) {
                            echo $this->paginationControl($this->books, 'Sliding', 'page/pagination.phtml');
                        } else {
                            
                        }
                        ?>     
                    </td>
                </tr>

            </table>
        </div>
    </div></div>
<div class="clear"></div>
<div>
<?= $this->render("video/menu.phtml") ?>
</div>

<script>
    $(".video_active").click(function () {
        var id = $(this).attr("id");
        var rel = $(this).attr("rel");
        $.ajax({
            url: "<?= $this->baseUrl("/admin/video/active") ?>",
            method: "POST",
            data: {id: id, active:rel},
            dataType: "html",
            success:function(msg){
                if(rel==1){
                   var strVar="";
                            strVar += "<a id=\""+id+"\" rel=\"2\" class=\"video_active\" href=\"javascript:void(0)\">";
                             strVar += "                                    <span class=\"label\">Inactive<\/span>";
                            
                            strVar += "                                <\/a>";
                            $("#active_"+id).html(strVar);
                  
                } else {
                      var strVar="";
                            strVar += "<a id=\""+id+"\" rel=\"1\" class=\"video_active\" href=\"javascript:void(0)\">";
                           strVar += "                                    <span class=\"label label-success\">Active<\/span>";
                            strVar += "                                <\/a>";
                            $("#active_"+id).html(strVar);
                }
                
            }
        });
        return false;
    });
</script>