
<script type="text/javascript" src="<?php echo $this->baseurl();  ?>/template/fckeditor/fckeditor.js"></script>

<script type="text/javascript" src="<?php echo $this->baseurl();  ?>/js/AJAX_2.js"></script>
<script>

</script>
 <?php
	
     
	function hop_option()
	{
            
           
             
         
                $idmenu1= Zend_Registry::get('idmenu');
       
                $db=Zend_Registry::get('connectDB'); 
                $sql = "SELECT * FROM `menu` where parent_id like '' and category_id='$idmenu1' and thuocloai like '1' ";
                $stml= $db->prepare($sql);
                $stml->execute();
		
		echo "<select name=\"menu_id\" class=\"validate[required] text-input\">";
		echo "<option value=\"\">Cấp độ</option>";
		while ($result=$stml->fetch(PDO::FETCH_ASSOC)) 
		{
			echo "<option value=\"$result[id]\">";
				echo $result['title'];
			echo "</option>";
			
				hop_option_de_quy($result['id'],0);
			
		}
		echo "</select>";
	}
function hop_option_de_quy($id,$so)
	{
            $idmenu= Zend_Registry::get('idmenu');
            $db1=Zend_Registry::get('connectDB'); 
		$so++;
		$kt="";
		for($i=1;$i<=$so;$i++)
		{
			$kt=$kt."&DoubleRightArrow;&DoubleRightArrow;&DoubleRightArrow;";
		}
                
                $sql1 = "SELECT * FROM `menu` where parent_id ='$id' and category_id='$idmenu' and thuocloai like '1'";
                $stml1= $db1->prepare($sql1);
                $stml1->execute();
		
		 while ($result1=$stml1->fetch(PDO::FETCH_ASSOC)) {
			echo "<option value='$result1[id]'>";
				echo $kt;
				echo $result1['title'];
			echo "</option>";
			
			
			
				hop_option_de_quy($result1['id'],$so);
			
		}
	}
       
?>
<div class="row-fluid sortable">
<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2> Đăng tin miễn phí</h2>
        
  </div>
     <div class="box-content">
         <h4>Để được đăng tin vip hiển thị trên trang chủ website chúng tôi. Xin vui lòng soạn <a href="javascrip:void(0)" style="color: #F00;">TINVIP ID gửi 6577 <br>(vd: TINVIP 1234 gửi 6577) </a>hoặc<a href="<?php echo $this->baseurl(); ?>/lien-he.html" title="liên hệ" style="color: #F00;"> liên hệ</a> với chúng tôi  vào số hotline : <a href="<?php echo $this->baseurl(); ?>/lien-he.html" title="liên hệ" style="color: #F00;">0974.547.155</a></h4>
         <br>
<form action="" method="post" enctype="multipart/form-data" name="tt_mh" id="tt_mh" onsubmit="return checkInput();" class="form-horizontal">
    
     <div class="control-group">
        <label class="control-label" for="selectError">Chọn khu vực</label>
        <div class="controls">
            <select name="dictrict_id"  id="dictrict_id">
                      <option value="">------ Chọn khu vực ------</option>
            <?php
           
           foreach($this->bokk as $val)
            {
               
                $id=$val['id'];
                $title=$val['category'];
                
               
                        echo "<option value='$id' >";
				echo $title;
			echo "</option>";
            }
            ?>
           </select>
             <div class="warning" id="dictrict_idError">Vui lòng chọn khu vực đăng tin của bạn</div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="selectError">Chọn danh mục</label>
        <div class="controls">
          <select name="category_id" id='category_id'>
                      <option value="">------ Chọn danh mục ------</option>
            <?php
           
            
           $idmenu=$this->idmenu;
           Zend_Registry::set('idmenu', $idmenu);
          // static $idmenu;
           foreach($this->bookss as $val)
            {
               
                $id=$val['id'];
                $title=$val['title'];
                 if ($idmenu==$id){$sl="selected";}else{$sl="";}
               
                        echo "<option value='$id' $sl>";
				echo $title;
			echo "</option>";
            }
            ?>
           </select>
            <div class="warning" id="category_idError">Vui lòng chọn danh mục</div>
        </div>
    </div>
 
 
  <script>
            $(document).ready(function(  ){
                $("select option:selected").each(function () {
                    $("div#div1").load("<?php echo $this->baseUrl(); ?>/default/register/menu?id=" + $(this).val());
                });	
            });
	
            $("select#category_id").change(function () {
                var str = "";
                $("select option:selected").each(function () {
                    str += $(this).val() + " ";
                });
               // $("div#div2").text(str);
            })
            .change(function(  ){
                $("div#div1").load("<?php echo $this->baseUrl(); ?>/default/register/menu?id=" + $(this).val());
                
            });
        </script>





    <div class="control-group">
        <label class="control-label" for="selectError">Chọn menu</label>
        <div class="controls">
           <div id="div1" style="float: left; margin: 2px 10px 0px 0px">
                <select name="">
                    <option>--- Chọn menu ---</option>
                </select>
            </div>
            <div id="div2" style="margin: 2px 10px 0px 0px"></div>
           <div class="warning" id="parent_idError">Vui lòng chọn menu</div>
        </div>
    </div>
       
        <input name="members" type="hidden" value=" <?php echo $this->username;    ?>" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4">
    <div class="control-group">
                  <label class="control-label" for="typeahead">Tiêu đề </label>
                  <div class="controls">
                    <input name="title" type="text" class="span6 typeahead" id="title"  placeholder="Nhập tiêu đề sản phẩm của bạn (*)" data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    <div class="warning" id="titleError">Vui lòng nhập tiêu đề </div>
                 </div>
    </div>
    
     <div class="control-group">
      <label class="control-label" for="fileInput">Hình ảnh</label>
      <div class="controls">
            <?php echo $this->formFile('images');?>
          <div class="warning" id="imagesError">Vui lòng chọn hình ảnh</div>
      </div>
    </div>
    <div class="control-group">
                  <label class="control-label" for="typeahead">Mô tả </label>
                  <div class="controls">
                   
                      <textarea name="description" cols="70" rows="10" class="span6 typeahead" id="description" placeholder="Nhập mô tả tóm tắt sản phẩm (*)" ></textarea>
                    <div class="warning" id="descriptionError">Vui lòng nhập mô tả </div>
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Giá bán (VNĐ) </label>
                  <div class="controls">
                      <input name="price" type="text" class="span6 typeahead" id="typeahead" placeholder="Giá sản phẩm của bạn (lưu ý chỉ nhập số)"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
	</div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Trạng thái </label>
                  <div class="controls">
                    <input name="state" type="text" class="span6 typeahead" id="typeahead" placeholder="Còn hàng, hết hàng, đã qua sử dụng ...." data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Xuất xứ </label>
                  <div class="controls">
                    <input name="made_in" type="text" class="span6 typeahead" id="typeahead" placeholder="Việt Nam, Hàn Quốc, Nhật Bản ...." data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Khuyến mãi </label>
                  <div class="controls">
                    <input name="sales" type="text" class="span6 typeahead" id="typeahead"  placeholder="" data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Description </label>
                  <div class="controls">
                   
                     <textarea name="dis" cols="70" rows="10" class="span6 typeahead"  id="typeahead" placeholder="Nhập description tối ưu hóa với bộ máy tìm kiếm google"></textarea>
               
                  </div>
    </div>
     <div class="control-group">
                  <label class="control-label" for="typeahead">Keywords </label>
                  <div class="controls">
                   
                     <textarea name="key" cols="70" rows="10" class="span6 typeahead" id="typeahead" placeholder="Nhập keyword tối ưu hóa với bộ máy tìm kiếm google" ></textarea>
               
                  </div>
    </div>
       
     
    <div class="control-group">
                  <label class="control-label" for="typeahead">Captcha </label>
                  <div class="controls">
                      <label><?php echo $this->captcha; ?></label>
                    
                    
                      <input name="captcha" type="text" class="span6 typeahead" id="captcha"  placeholder="Nhập ký tự ở trên (*)" >
                    <?php echo $this->formHidden('captcha_id',$this->captchaID)?>
                <div class="warning" id="captchaError">Vui lòng nhập captcha</div>
                  </div>
    </div>
    
    <div class="control-group" id="content">
              <label class="control-label" for="textarea2">Nội dung</label>
              <div class="controls">
                    <div id="div_vn_afc">
              <script type="text/javascript">
                    var oFCKeditor = new FCKeditor('content');
                     oFCKeditor.ToolbarSet	= 'Footer';
                    oFCKeditor.BasePath = "<?php echo $this->baseUrl(); ?>/template/fckeditor/";
                    oFCKeditor.Width	= 600 ;
                    oFCKeditor.Height	= 300 ;
                    oFCKeditor.Value="";
                    oFCKeditor.Config["EnterMode"]		= "br" ;
                    oFCKeditor.Create();
                    document.getElementById('xEnter').value = "br" ;
                    //document.getElementById("noidung").value=jljl;
            </script>
            </div>
            
              </div>
	</div>   
     
        
        <div class="form-actions">
                  <button type="submit" class="btn btn-primary" id="posting">Đăng Tin</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
      
    </form>
     </div>
</div></div>
<div class="clear"></div>
 <h4>Để được đăng tin vip hiển thị trên trang chủ website chúng tôi. Xin vui lòng soạn <a href="javascrip:void(0)" style="color: #F00;">TINVIP ID gửi 6577 <br>(vd: TINVIP 1234 gửi 6577) </a>hoặc<a href="<?php echo $this->baseurl(); ?>/lien-he.html" title="liên hệ" style="color: #F00;"> liên hệ</a> với chúng tôi  vào số hotline : <a href="<?php echo $this->baseurl(); ?>/lien-he.html" title="liên hệ" style="color: #F00;">0974.547.155</a></h4>