 
<script type="text/javascript" src="<?= $this->baseUrl() ?>/template/js/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseurl(); ?>/js/AJAX_3.js"></script>

<style>
    
#content {
    margin-bottom: 10px;
    min-height: 100px;
    
    padding: 0;
}
.form-control{border-radius: 0}
#tt_mh span{color: red}
#tt_mh .send{background: #179cfe; border-color: #ccc}
.contact-form img {
    border: 1px solid #ddd;
    color: #999;
    display: block;
  
    outline: medium none;
   
    resize: none; float: left;margin-right:10px;
    
}
</style>

<div class="title"><a href="<?= $this->baseUrl() ?>">Trang chủ</a> » &nbsp; <a href="<?= $this->baseUrl("/lien-he.html") ?>"><?php echo "Liên Hệ"; ?></a></div>
<div class="product-list">
<div class="col-md-12 contact_right">
 
    <div class="contact-form">
        <form action="" method="post" enctype="multipart/form-data" name="tt_mh" id="tt_mh"  class="form-horizontal">

                            <div class="form-group">

                                <label for="inputEmail" class="control-label col-xs-1">
                                      
                                    </label>

                                <div class="col-xs-9">
                                     <?=  "Tên đầy đủ "  ?>  <span> (*) </span>
                                    <input name="fullname" required="" type="text" class="form-control" id="full_name"  placeholder="<?= "Nhập tên của bạn " ?> " > 
                                    

                                </div>
                                   

                            </div>

                            <div class="form-group">

                                <label for="inputEmail" class="control-label col-xs-1"></label>

                                <div class="col-xs-9">
                                    Email <span> (*) </span>
                                    <input name="email" type="email" required="" class="form-control" id="email"  data-provide="typeahead" placeholder="<?= "Nhập email của bạn " ?> ">
                                   

                                </div>

                            </div>


                            <div class="form-group">

                                <label for="inputEmail" class="control-label col-xs-1"></label>

                                <div class="col-xs-9">
                                    <?=  "Số ĐT"  ?> <span> (*) </span>
                                    <input name="phone" required="" type="tel" class="form-control" id="phone"  data-provide="typeahead"  placeholder="<?= "Nhập số diện thoại của bạn " ?> ">

                                   

                                </div>

                            </div>
                            <div class="form-group">

                                <label for="inputEmail" class="control-label col-xs-1"> </label>

                                <div class="col-xs-9">
                                    <?= "Địa chỉ " ?> <span> (*) </span>
                                    <input name="address" type="text" required="" class="form-control" id="address" placeholder="<?= "Nhập địa chỉ của bạn " ?> " >
                                   

                                </div>

                            </div>

                            <div class="form-group">

                                <label for="inputEmail" class="control-label col-xs-1"></label>

                                <div class="col-xs-9">
                                    <?= " Nội dung " ?> <span> (*) </span>
                                    <textarea name="content" class="form-control  custom-control" placeholder="Nhập nội dung" required="" rows="3" style="resize:none"></textarea> 
                                    
                                </div>

                            </div>

                            <div class="form-group">

                                <label for="inputEmail" class="control-label col-xs-1"></label>

                                <div class="col-xs-9">
                                   
                                    <?php echo $this->captcha; ?>
                                    <?php echo $this->formHidden('captcha_id', $this->captchaID) ?>
                                    <input required="" name="captcha" type="text" class="col-md-5 pull-left" style=" height: 48px; border: 1px solid #ccc" id="captcha"  placeholder="  <?= "Nhập mã captcha " ?> " >

                                </div>

                            </div>
                            <div class="form-group">
<label for="inputEmail" class="control-label col-xs-1"></label>
                                <div class="col-xs-10 text-center">

                                    <button type="submit" class="btn btn-primary send">Gửi thông tin <i class="fa fa-arrow-right"></i> </button>
                                    <button class="btn btn-primary send" type="reset">Xóa trắng <i class="fa fa-close"></i> </button>

                                </div>

                            </div>

                        </form>
    </div>
</div>
<div class="col-md-12">
    
    <?php $list = $this->book;
    echo $list[0]['content']; ?>

</div>
    <div class="clearfix"></div>

</div>



