<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/simpletreemenu.js"></script>
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl() ?>/css/simpletree.css" />
<?php 
    function menu_doc__() 
    {
        $vie= new Zend_View();
        $base= $vie->baseurl();
       
       
        
      
        
        $cnDB2= Zend_Registry::get('connectDB'); 
       
            $tv1="select * from  add_page where cat_page=1 and cat_page_id like '' and active=1 and id not in (57) order by position ASC, id ASC  "; 
             $stml2= $cnDB2->prepare($tv1); 
            $stml2->execute();
          
            
             
	$stt=1;
         echo "<ul id=\"treemenu1\" class=\"treeview\">";
          echo " <li> <a href=\"$base\"> Trang chủ </a></li>";
	 while ($tv_21=$stml2->fetch(PDO::FETCH_ASSOC)) { 
            
	 $dm=$tv_21['id'];

			$danhmuc=$tv_21['title'];
			$url_tt= khongdau($danhmuc);
                       
			  echo " <li> <a href=\"$base/pages/$url_tt-$dm.html\"> $danhmuc </a>";
		
     
                          echo "<ul class=\"\">";
				
                                $tv11="select * from add_page where cat_page_id like '$dm' and  active=1 order by position asc, id ASC";
                                $stml21= $cnDB2->prepare($tv11);
                                $stml21->execute();
                                                                
				while ($tv_2=$stml21->fetch(PDO::FETCH_ASSOC)) 
				{
                                    //var_dump($tv_2);exit;
					$id=$tv_2['id'];
					$ten=$tv_2['title'];
					 $url=  khongdau($ten);
					$link_menu="$base/pages/$url-$id.html";
					echo "<li>";
						echo "<a href=\"$link_menu\" title=\"$ten\">"; 
							echo $tv_2['title'];
						echo "</a>";
						$xacdinh_menu_con_doc= xacdinh_menu_con_doc__($id);
						if($xacdinh_menu_con_doc=="co")
						{
							echo "<ul>";
                                                        dequy_menu_doc($id);
							echo "</ul>";
						}
						else
						{
						}
					echo "</li>";
				}
                                
                                echo "</ul>";
                                
            	  echo" </li>";
     
	
                                
                    
        
                $stt++;} 

                
                 echo"  </ul>";
                
          

        
    }
    
    
     function xacdinh_menu_con_doc__($id)
    {       $cnDB= Zend_Registry::get('connectDB'); 
            $query="select * from menu where parent_id='$id' and active=1 order by position asc";
            $stml= $cnDB->prepare($query);
            $stml->execute();
            $result=$stml->rowCount();
           // echo $result;
            if($result!=0){return "co";}else{return "khong";}
    }
    function dequy_menu_doc__($id)
    {
            $vie= new Zend_View();
        $base= $vie->baseurl();
            $cnDB1= Zend_Registry::get('connectDB'); 
            $tv="select * from menu where parent_id='$id' and active=1 order by position ASC";
             $stml1= $cnDB1->prepare($tv);
            $stml1->execute();

             while ($result1=$stml1->fetch(PDO::FETCH_ASSOC)) {
                    $id=$result1['id'];
                    $ten=$result1['title'];
                     $url=khongdau($ten);
                    $link_menu="$base/danh-muc/$url-$id.html";
                    echo "<li>";
                            echo "<a href=\"$link_menu\">";
                                    echo $result1['title'];
                            echo "</a>";
                            $xacdinh_menu_con_doc= xacdinh_menu_con_doc__($id);
                            if($xacdinh_menu_con_doc=="co")
                            {
                                    echo "<ul>";
                                   dequy_menu_doc($id);
                                    echo "</ul>";
                            }
                            else
                            {
                            }
                    echo "</li>";
            }
    }
   
?>

<div class="title1">
    <div  style="padding-top:10px; padding-left: 20px">Sitemap</div>
    

</div>
<div class="sanpham" align="left" style="margin: 0px">
    	
    <a href="javascript:ddtreemenu.flatten('treemenu1', 'expand')"><h1>Hiển thị tất cả</h1></a> 
<?php menu_doc__(); ?>

</div>
<script type="text/javascript">

//ddtreemenu.createTree(treeid, enablepersist, opt_persist_in_days (default is 1))

ddtreemenu.createTree("treemenu1", "expand")
ddtreemenu.createTree("treemenu2", false)

</script>

