 <?php 
            
             
             foreach($this->bookss as $val1)
            {
                
            
                $images=$val1['images']; 
                $id=$val1['id'];
                 $mask = APPLICATION_PATH."/../public_html/Upload/$images"; 
                array_map("unlink",glob($mask)); 
                $del= new Admin_Model_Page();
                
                $del->delete_Pages($id);
                trang_truoc();
                        
            }
?>