<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index/">Thêm loại trang</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpage/">Danh sách loại trang</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/addpages/">Thêm trang mới</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpages/">Danh sách  trang</a>
        </li>
</ul>
</div>
<?php
	
	function hop_option_de_quy($id,$so)
	{
            $db1=Zend_Registry::get('connectDB'); 
		$so++;
		$kt="";
		for($i=1;$i<=$so;$i++)
		{
			$kt=$kt."&DoubleRightArrow;&DoubleRightArrow;&DoubleRightArrow;";
		}
                
                $sql1 = "SELECT * FROM `add_page` where cat_page_id ='$id' ";
                $stml1= $db1->prepare($sql1);
                $stml1->execute();
		
		 while ($result1=$stml1->fetch(PDO::FETCH_ASSOC)) {
			echo "<option value='$result1[id]'>";
				echo $kt;
				echo $result1['title'];
			echo "</option>";
			
			
			
				hop_option_de_quy($result1['id'],$so);
			
		}
	}
	function hop_option()
	{
                $db=Zend_Registry::get('connectDB'); 
                $sql = "SELECT * FROM `add_page` where cat_page_id like '' ";
                $stml= $db->prepare($sql);
                $stml->execute();
		
		echo "<select name=\"cat_page_id\" >";
		echo "<option value=\"\">Cấp đầu</option>";
		while ($result=$stml->fetch(PDO::FETCH_ASSOC)) 
		{
			echo "<option value=\"$result[id]\">";
				echo $result['title'];
			echo "</option>";
			
				hop_option_de_quy($result['id'],0);
			
		}
		echo "</select>";
	}


?>
<div class="row-fluid sortable">
<div class="box span12">
 <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
 <div class="box-content">
<form action="" method="post" enctype="multipart/form-data" name="tt_mh" id="tt_mh"  onsubmit="return checkInput(); " class="form-horizontal">
     
       
      
       <div class="control-group">
                  <label class="control-label" for="typeahead">Cấp độ </label>
                  <div class="controls">
                    <?php hop_option(); ?>
                    
               
                  </div>
	</div>
        
        
         <div class="control-group">
                  <label class="control-label" for="typeahead">Tiêu đề </label>
                  <div class="controls">
                    <input name="title" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    
          <div class="control-group">
                  <label class="control-label" for="typeahead">Vị trí </label>
                  <div class="controls">
                    <input name="position" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
        
    
    
       
    
        <div class="control-group">
            <label class="control-label">Hiển thị</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="active" id="optionsRadios1" value="1" checked="">
                    Có
              </label>
              <div style="clear:both"></div>
              <label class="radio">
                    <input type="radio" name="active" id="optionsRadios2" value="2">
                   Không
              </label>
            </div>
	</div>
    
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Description </label>
                  <div class="controls">
                   
                     <textarea name="dis" cols="70" rows="10" class="span6 typeahead" id="typeahead" ></textarea>
               
                  </div>
    </div>
     <div class="control-group">
                  <label class="control-label" for="typeahead">Keywords </label>
                  <div class="controls">
                   
                     <textarea name="key" cols="70" rows="10" class="span6 typeahead" id="typeahead" ></textarea>
               
                  </div>
    </div>
    
        <div class="control-group">
            <label class="control-label">Phân loại</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="cat_page" id="optionsRadios1" value="1" checked="">
                    Chứa sản phẩm
              </label>
              <div style="clear:both"></div>
              <label class="radio">
                    <input type="radio" name="cat_page" id="optionsRadios2" value="2">
                   Chứa nội dung
              </label>
            </div>
	</div>
    
     <script>
$(document).ready(function(){
  $("#optionsRadios1").click(function(){
    $("#content").hide();
  });
  $("#optionsRadios2").click(function(){
    $("#content").show();
  });
});
</script>
        <div class="control-group" id="content">
              <label class="control-label" for="textarea2">Nội dung</label>
              <div class="controls">
                    <div id="div_vn_afc">
              <script type="text/javascript">
                    var oFCKeditor = new FCKeditor('content');
                    oFCKeditor.BasePath = "<?php echo $this->baseUrl(); ?>/fckeditor/";
                    oFCKeditor.Width	= 600 ;
                    oFCKeditor.Height	= 300 ;
                    oFCKeditor.Value="";
                    oFCKeditor.Config["EnterMode"]		= "br" ;
                    oFCKeditor.Create();
                    document.getElementById('xEnter').value = "br" ;
                    //document.getElementById("noidung").value=jljl;
            </script>
            </div>
            <div id="div_en_afc" style="display:none">
              <script type="text/javascript">
                    var oFCKeditor = new FCKeditor('txt_noidung_en');
                    oFCKeditor.BasePath = "<?php echo $this->baseUrl(); ?>/fckeditor/";
                    oFCKeditor.Width	= 600 ;
                    oFCKeditor.Height	= 300 ;
                    oFCKeditor.Value="";
                    oFCKeditor.Config["EnterMode"]		= "br" ;
                    oFCKeditor.Create();
                    document.getElementById('xEnter').value = "br" ;
                    //document.getElementById("noidung").value=jljl;
            </script>
            </div>
              </div>
	</div>
         <div class="form-actions">
                  <button type="submit" class="btn btn-primary">Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
    </form>
 </div>
</div>
</div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index/">Thêm loại trang</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpage/">Danh sách loại trang</a> <span class="divider">/</span>
        </li>
         <!--         <li>
                <a href="<?php //echo $this->baseUrl(); ?>/admin/page/addpages/">Thêm trang mới</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php //echo $this->baseUrl(); ?>/admin/page/listpages/">Danh sách  trang</a>
        </li>-->
</ul>
</div>