<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index/">Thêm loại trang</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpage/">Danh sách loại trang</a> <span class="divider">/</span>
        </li>
                <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/addpages/">Thêm trang mới</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpages/">Danh sách  trang</a>
        </li>
</ul>
</div>

<div class="row-fluid sortable">
<div class="box span12">
    
<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
   <div class="box-content"> 
<table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
    <tr>
  
    <th>Tiêu đề</th>
    <th>Vị trí</th>
    <th>Hiển thị</th>
    <th>Phân loại</th>
    
     <th>Select</th>
    <th >Xóa</th>
    <th >Sửa</th>
  </tr>
  
    </thead>
  <?php
	
   

    function hop_option_de_quy($id_,$so)
	{
       
        $view= new Zend_View();
        $base= $view->baseUrl();
            
               $db1=Zend_Registry::get('connectDB'); 
		$so++;
		$kt="&nbsp;";
		for($i=1;$i<=$so;$i++)
		{
			$kt=$kt."<span class=\"icon32 icon-darkgray icon-treeview-corner\" title=\.icon  .icon-treeview-corner \"></span>";
		}
                  
                $sql1 = "SELECT * FROM `add_page` where cat_page_id ='$id_' "; 
                 
                $stml1= $db1->prepare($sql1);
                $stml1->execute();
		
		 while ($result1=$stml1->fetch(PDO::FETCH_ASSOC)) {
                     $id_1=$result1['id'];
			 echo "<tr id=\"row_$id_1\">";
                    
                       
			 if ($result1['active']==1){
                             $ck='checked';
                             }
                             else {$ck='';}
                             
                              if ($result1['cat_page']==1){
                                 $pl='Chứa sản phẩm';
                                 }
                             else {$pl='Chứa nội dung';}
                             
                             $del1=$view->url(array('action'=>'deletepage','id'=>$result1['id']));
                              $edit1=$view->url(array('action'=>'editpage','id'=>$result1['id']));
                            $update_active_1=$view->url(array('action'=>'useractive','id'=>$id_1,'active'=>0));
                            $update_inactive_1=$view->url(array('action'=>'useractive','id'=>$id_1,'active'=>1));

                             $status_1=$result1['active'];
                            if($status_1==1){$tt_1="<a href=\"javascript:void(0)\" id='active_$id_1' class=\"label label-success\" >Active</a>  <a href=\"javascript:void(0)\" id='inactive_$id_1' class=\"label\" style='display:none'>Inactive</a>";}
                            else {$tt_1="<a href=\"javascript:void(0)\" id='active_$id_1' class=\"label label-success\" style='display:none' >Active</a> <a href=\"javascript:void(0)\" id='inactive_$id_1' class=\"label\">Inactive</a>";}

			echo "<td >";echo $kt;echo $result1['title']; echo "</td>";
                    
			  echo "<td> $result1[position]</td>";
                         echo "<td id=\"demo_active_$id_1\">$tt_1</td>";
                        echo "<td> $pl</td>";
			echo " <td><input type='checkbox'  ></td>";
                         echo "<td ><a href='#' class=\"btn btn-danger\" id=\"row_del_$id_1\"><i class=\"icon-trash icon-white\"></i></a></td>";
                        echo "<td ><a href='$edit1' class=\"btn btn-info\"><i class=\"icon-edit icon-white\"></i> </a></td>";	
			
			
				
                    echo "</tr>";
                    ?>
                   <script>
            $( "#row_del_<?= $id_1 ?>" ).live('click',function(event_ref) {  event_ref.preventDefault();
           if (confirm('Are you sure you wish to delete this record?')){
                $.post('<?= $del1 ?>');
                $( "#row_<?= $id_1 ?>" ).hide(2000);
          }
    });
    
    
    $( "#active_<?= $id_1 ?>" ).live('click',function() {  
           
            $.post('<?= $update_active_1 ?>');
               
               $( "#demo_active_<?= $id_1 ?>" ).empty();
               $( "#demo_active_<?= $id_1 ?>" ).append( "<a href=\"javascript:void(0)\" id='inactive_<?= $id_1 ?>' class=\"label\">Inactive</a>" );
              
         
    });
    
    $( "#inactive_<?= $id_1 ?>" ).live('click',function() {  
           
            $.post('<?= $update_inactive_1 ?>');
               
               $( "#demo_active_<?= $id_1 ?>" ).empty();
               $( "#demo_active_<?= $id_1 ?>" ).append( "<a href=\"javascript:void(0)\" id='active_<?= $id_1 ?>' class=\"label label-success\">Active</a>" );
          
    });
</script>

<?php
                   hop_option_de_quy($id_1, $so);
			
                    
		}
	}
	?>
      <?php
      $stt=1;
      $url=$this->baseUrl();
      foreach($this->books as $val)
        {
          $id=$val['id'];
          $edit=$this->url(array('action'=>'editpage','id'=>$id));
          $del=$this->url(array('action'=>'deletepage','id'=>$id));
         
          
           $update_active=$this->url(array('action'=>'useractive','id'=>$id,'active'=>0));
          $update_inactive=$this->url(array('action'=>'useractive','id'=>$id,'active'=>1));
         
           $status=$val['active'];
          if($status==1){$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" >Active</a>  <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\" style='display:none'>Inactive</a>";}
          else {$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" style='display:none' >Active</a> <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\">Inactive</a>";}
           
          
          
           if ($val['cat_page']==1){
              $pl='Chứa sản phẩm';
          }
          else {$pl='Chứa nội dung';}
          ?>
    <tr id="row_<?= $id ?>">
      
   <?php  echo "<td align='center'>".$val['title']."</td>"; ?>

    <td> <?php echo $val['position']; ?></td>
   <td id="demo_active_<?= $id ?>">  <?php echo $tt; ?> </td>
    <td><?php echo $pl; ?></td>
   
     <td><input type='checkbox'  ></td>
   <td>
    
        <a class="btn btn-danger"  id="row_del_<?= $id ?>" href='#' >
	<i class="icon-trash icon-white"></i> 
	Delete
	</a>
    
    
    </td>
    <td ><a class="btn btn-info" href="<?php echo $edit;?>">
	<i class="icon-edit icon-white"></i>  
	Edit                                            
	</a>
    </td>
  </tr>
  <script>
            $( "#row_del_<?= $id ?>" ).live('click',function(event_ref) {  event_ref.preventDefault();
           if (confirm('Are you sure you wish to delete this record?')){
                $.post('<?= $del ?>');
                $( "#row_<?= $id ?>" ).hide(2000);
          }
    });
    
    
    $( "#active_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_active ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='inactive_<?= $id ?>' class=\"label\">Inactive</a>" );
              
         
    });
    
    $( "#inactive_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_inactive ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='active_<?= $id ?>' class=\"label label-success\">Active</a>" );
          
    });
</script>


  <?php
  $count = new Admin_Model_Page();
  $count = $count->count_page($id);
  if($count=='co'){      hop_option_de_quy($id, 0);}
 else {
    
}
  
  $stt++;} 
  
 // hop_option_de_quy($id,$so);
  ?>
  
 
  
  <tr ><td colspan="9">
          
      <?php 
      
      echo $this->paginationControl($this->books,  'Sliding', 'page/pagination.phtml');
     
      ?>     
      </td>
  </tr>
    
  
  
</table>
   </div>
</div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index/">Thêm loại trang</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpage/"> Danh sách loại trang</a> <span class="divider">/</span>
        </li>
              <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/addpages/">Thêm trang mới</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpages/">Danh sách  trang</a>
        </li>
</ul>
</div>