<?php
	
	function hop_option_de_quy($id,$so)
	{
            $db1=Zend_Registry::get('connectDB'); 
		$so++;
		$kt="";
		for($i=1;$i<=$so;$i++)
		{
			$kt=$kt."&DoubleRightArrow;&DoubleRightArrow;&DoubleRightArrow;";
		}
                
                $sql1 = "SELECT * FROM `add_page` where cat_page_id ='$id' and cat_page <> 2";
                $stml1= $db1->prepare($sql1);
                $stml1->execute();
		
		 while ($result1=$stml1->fetch(PDO::FETCH_ASSOC)) {
			echo "<option value='$result1[id]'>";
				echo $kt;
				echo $result1['title'];
			echo "</option>";
			
			
			
				hop_option_de_quy($result1['id'],$so);
			
		}
	}
	function hop_option()
	{
                $db=Zend_Registry::get('connectDB'); 
                $sql = "SELECT * FROM `add_page` where cat_page_id like '' and cat_page <> 2";
                $stml= $db->prepare($sql);
                $stml->execute();
		
		echo "<select name=\"cat_page_id\" >";
		echo "<option value=\"\">Cấp đầu</option>";
		while ($result=$stml->fetch(PDO::FETCH_ASSOC)) 
		{
			echo "<option value=\"$result[id]\">";
				echo $result['title'];
			echo "</option>";
			
				hop_option_de_quy($result['id'],0);
			
		}
		echo "</select>";
	}


?>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index/">Thêm loại trang</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpage/">Danh sách loại trang</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/addpages/">Thêm trang mới</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpages/">Danh sách  trang</a>
        </li>
</ul>
</div>




<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">
    
        
     <form action="" method="post" enctype="multipart/form-data" name="tt_mh" id="tt_mh"  class="form-horizontal">
 <div class="control-group">
        <label class="control-label" for="selectError">Tìm kiếm</label>
        <div class="controls">
            <input name="title" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" style="float: left; margin-right: 10px; width: 250px" >
            
           
        <div id="div1" style="float: left; margin: 2px 10px 0px 0px">
                 <?php hop_option(); ?>
            </div>
            
            <button type="submit" class="btn btn-primary" style="margin-top: 2px">Search</button>
        </div>
    </div>
            

   
                 
               
   
</form>
        
<table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
    <tr>
     <th >STT</th>
  
        <th >Tiêu đề</th>
        <th >Hình Ảnh</th>
    <th >Vị trí</th>
    <th >Hiển thị</th>
    <th >Thuộc danh mục</th>
    
     <th >Select</th>
    <th >Xóa</th>
    <th >Sửa</th>
    </thead>
  </tr>
  
  
  
      <?php
      $stt=1;
      $url=$this->baseUrl();
      foreach($this->books as $val)
        {
          
          $id=$val['id'];
           $menu=$val['menu'];
           
            $muser= new Admin_Model_Page();
       
           
          $edit=$this->url(array('action'=>'editpages','id'=>$id));
          $del=$this->url(array('action'=>'deletepages','id'=>$id));
           $update_active=$this->url(array('action'=>'pagesactive','id'=>$id,'active'=>0));
          $update_inactive=$this->url(array('action'=>'pagesactive','id'=>$id,'active'=>1));
          
            $status=$val['active'];
          if($status==1){$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" >Active</a>  <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\" style='display:none'>Inactive</a>";}
          else {$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" style='display:none' >Active</a> <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\">Inactive</a>";}
           
          
          
         
          ?>
  <tr id="row_<?= $id ?>">
      <td ><?php echo $stt;?></td>
   <?php  echo "<td align='center'>".$val['title']."</td>"; ?>

      <td> <img src="<?php echo $url;?>/Upload/<?php echo $val['images']; ?>" width="80" ></td>
    <td> <?php echo $val['position']; ?></td>
     <td id="demo_active_<?= $id ?>">  <?php echo $tt; ?> </td>
    <td><?php $muser->select_user($menu); ?></td>
   
     <td><input type='checkbox'  ></td>
    <td>
    
        <a class="btn btn-danger"  id="row_del_<?= $id ?>" href='#' >
	<i class="icon-trash icon-white"></i> 
	Delete
	</a>
    
    
    </td>
    <td ><a class="btn btn-info" href="<?php echo $edit;?>">
	<i class="icon-edit icon-white"></i>  
	Edit                                            
	</a>
    </td>
  </tr>
  <script>
            $( "#row_del_<?= $id ?>" ).live('click',function(event_ref) {  event_ref.preventDefault();
           if (confirm('Are you sure you wish to delete this record?')){
                $.post('<?= $del ?>');
                $( "#row_<?= $id ?>" ).hide(2000);
          }
    });
    
    $( "#active_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_active ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='inactive_<?= $id ?>' class=\"label\">Inactive</a>" );
              
         
    });
    
    $( "#inactive_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_inactive ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='active_<?= $id ?>' class=\"label label-success\">Active</a>" );
          
    });
</script>
  
  <?php $stt++;} ?>
  
 
  <tr ><td colspan="9">
          
      <?php 
      
      echo $this->paginationControl($this->books,  'Sliding', 'page/pagination.phtml');
     
      ?>     
      </td>
  </tr>
    
</table>
         
    </div> 
        
</div>
</div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/index/">Thêm loại trang</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpage/">Danh sách loại trang</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/addpages/">Thêm trang mới</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/page/listpages/">Danh sách  trang</a>
        </li>
</ul>
</div>