<?php if ($this->pageCount): ?>
<?php if($this->pageCount!=1) {?>
<div class="pagination pagination-centered" > 
     <ul class="navi">
         
<?php 
	if (isset($this->previous)){
  		echo '<li><a href="' . $this->url(array('page' => $this->previous)). '">  Previous</a> </li> ';
	}
	foreach ($this->pagesInRange as $page){
	   if ($page != $this->current){
	   		echo  '<li><a href="' . $this->url(array('page' => $page)). '">' . $page . '</a> </li> ';
	  }else{
	  	echo "<li class=\"active\"><a>".$page . '</a></li> ';
	  }
   }
	 if (isset($this->next)){
		echo '<li><a href="' . $this->url(array('page' => $this->next)) . '">Next </a></li>';
  	 }
  ?>
     </ul>
</div>
<?php } else {}?>
<?php endif; ?>
