<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/addpartners/">Thêm đối tác </a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/listpartners/">Danh sách đối tác </a> 
        </li>
         
         
</ul>
</div>



<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">

<?php
foreach ($this->books as $val)
{

  
    ?>
   
  
 
    
<form action='' method='post' enctype='multipart/form-data' name='tt_mh' id='tt_mh' class="form-horizontal"  >
    
     
    
    <div class="control-group hide">
                  <label class="control-label" for="typeahead">Tiêu đề </label>
                  <div class="controls">
                      <input name="title" value="<?php  echo $this->escape($val['title']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
    </div>
    
    <div class="control-group">
      <label class="control-label" for="fileInput">Hình ảnh</label>
      <div class="controls">
            <?php echo $this->formFile('images');?>
          <div class="clear"></div>
          <img src="<?php echo $this->baseUrl(); ?>/Upload/<?php  echo $this->escape($val['images']); ?>" width="190">
          <input name="images_hiden" type="hidden" id="name"  size="70" class="text"  value="<?php  echo $this->escape($val['images']); ?>"/>
      </div>
    </div>
    <div class="control-group hide">
                  <label class="control-label" for="typeahead">Mô tả </label>
                  <div class="controls">
                   
                     <textarea name="description" cols="70" rows="10" class="span6 typeahead" id="typeahead" ><?php  echo $this->escape($val['description']); ?></textarea>
               
                  </div>
    </div>
    
    <div class="control-group hide">
                  <label class="control-label" for="typeahead">Link </label>
                  <div class="controls">
                    <input name="link" value="<?php  echo $this->escape($val['link']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    
            
           
           
                     
                     
         
             
    <div class="control-group">
                  <label class="control-label" for="typeahead">Vị trí </label>
                  <div class="controls">
                    <input name="position" value="<?php  echo $this->escape($val['position']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" >
                    
               
                  </div>
	</div>
    
    
    
    
        <div class="form-actions">
                  <button type="submit" class="btn btn-primary">Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
          
    
      </form>
<?php
    }
?>
    </div></div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/addpartners/">Thêm đối tác </a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/listpartners/">Danh sách đối tác </a> 
        </li>
         
         
</ul>
</div>