<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/addside/">Thêm sildeshow </a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/listside/">Danh sách sildeshow </a> 
        </li>
         
         
</ul>
</div>

<div class="row-fluid sortable">
<div class="box span12">
    
<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
   <div class="box-content"> 
<table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
    <tr><th >STT</th>
  
    <th>Tiêu đề</th>
    <th>Hình ảnh</th> 
    <th>Mô tả</th>
    <th>Vị trí</th>
    
   
    
     <th>Link</th>
    <th >Xóa</th>
    <th >Sửa</th>
  </tr>
  
    </thead>
  
      <?php
      $stt=1;
      $url=$this->baseUrl();
      foreach($this->books as $val)
        {
          $id=$val['id'];
          $edit=$this->url(array('action'=>'editside','id'=>$id));
          $del=$this->url(array('action'=>'deleteside','id'=>$id));
          
          ?>
    <tr id="row_<?= $id ?>">
      <td ><?php echo $stt;?></td>
   <?php  echo "<td align='center'>".$val['title']."</td>"; ?>
   <td> <img src="<?php echo $url;?>/Upload/<?php echo $val['images']; ?>" width="80" ></td>
    <td> <?php echo $val['description']; ?></td>
   <td> <?php echo $val['position']; ?></td>
    <td> <?php echo $val['link']; ?></td>
   
    
    <td>
    
        <a class="btn btn-danger"  id="row_del_<?= $id ?>" href='#' >
	<i class="icon-trash icon-white"></i> 
	Delete
	</a>
    
    
    </td>
    <td ><a class="btn btn-info" href="<?php echo $edit;?>">
	<i class="icon-edit icon-white"></i>  
	Edit                                            
	</a>
    </td>
  </tr>
  <script>
            $( "#row_del_<?= $id ?>" ).live('click',function(event_ref) {  event_ref.preventDefault();
           if (confirm('Are you sure you wish to delete this record?')){
                $.post('<?= $del ?>');
                $( "#row_<?= $id ?>" ).hide(2000);
          }
    });
</script>
  <?php $stt++;} ?>
  
 
  
  <tr ><td colspan="9">
          
      <?php 
      if($stt>=15) {
      echo $this->paginationControl($this->books,  'Sliding', 'page/pagination.phtml');}
      else {}
      ?>     
      </td>
  </tr>
    
</table>
   </div>
</div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/addside/">Thêm sildeshow </a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/side/listside/">Danh sách sildeshow </a> 
        </li>
         
         
</ul>
</div>