<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Home</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addcategory/">Adding root</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listcategory/">List the original list</a> <span class="divider">/</span>
        </li>
<!--         <li>
                <a href="<?php //echo $this->baseUrl(); ?>/admin/product/addmenu/">Add menu</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php //echo $this->baseUrl(); ?>/admin/product/listmenu//">List menu</a><span class="divider">/</span>
        </li>-->
        
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addproducts/idmenu/0">Add products</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listproducts/">Product List</a>
        </li>
</ul>
</div>