<!--Categories Part Start-->

<?php 
function online()
{
    $rip = $_SERVER['REMOTE_ADDR'];
    $sd = time();
    $count = 1;
    $maxu = 1;
    
    $file1 = APPLICATION_PATH."/../counter/online.log";
    $lines = file($file1);
    $line2 = "";

    foreach ($lines as $line_num => $line)
    {
        if($line_num == 0)
        {
            $maxu = $line;
        }
        else
        {
            $fp = strpos($line,'****');
            $nam = substr($line,0,$fp);
            $sp = strpos($line,'++++');
            $val = substr($line,$fp+4,$sp-($fp+4));
            $diff = $sd-$val;

            if($diff < 300 && $nam != $rip)
            {
                $count = $count+1;
                $line2 = $line2.$line;
            }
        }
    }

    $my = $rip."****".$sd."++++\n";
    if($count > $maxu)
    $maxu = $count;

    $open1 = fopen($file1, "w");
    fwrite($open1,"$maxu\n");
    fwrite($open1,"$line2");
    fwrite($open1,"$my");
    fclose($open1);
    $count=$count;
    $maxu=$maxu+200;
    
    return $count;
}

///////////////////////
    $ip = $_SERVER['REMOTE_ADDR'];
    
    $file_ip = fopen(APPLICATION_PATH."/../counter/ip.txt", 'rb');
    while (!feof($file_ip)) $line[]=fgets($file_ip,1024);
    for ($i=0; $i<(count($line)); $i++) {
        list($ip_x) = split("\n",$line[$i]);
        if ($ip == $ip_x) {$found = 1;}
    }
    fclose($file_ip);
    
    if (!($found==1)) {
        $file_ip2 = fopen(APPLICATION_PATH."/../counter/ip.txt", 'ab');
        $line = "$ip\n";
        fwrite($file_ip2, $line, strlen($line));
        $file_count = fopen(APPLICATION_PATH."/../counter/count.txt", 'rb');
        $data = '';
        while (!feof($file_count)) $data .= fread($file_count, 4096);
        fclose($file_count);
        list($today, $yesterday, $total, $date, $days) = split("%", $data);
        if ($date == date("Y m d")) $today++;
            else {
                $yesterday = $today;
                $today = 1;
                $days++;
                $date = date("Y m d");
            }
        $total++;
        $line = "$today%$yesterday%$total%$date%$days";
        
        $file_count2 = fopen(APPLICATION_PATH."/../counter/count.txt", 'wb');
        fwrite($file_count2, $line, strlen($line));
        fclose($file_count2);
        fclose($file_ip2);
      }
      
      
    function today()
    {
        $file_count = fopen(APPLICATION_PATH."/../counter/count.txt", 'rb');
        $data = '';
        while (!feof($file_count)) $data .= fread($file_count, 4096);
        fclose($file_count);
        list($today, $yesterday, $total, $date, $days) = split("%", $data);
        return $today;
    }
    function yesterday()
    {
        $file_count = fopen(APPLICATION_PATH."/../counter/count.txt", 'rb');
        $data = '';
        while (!feof($file_count)) $data .= fread($file_count, 4096);
        fclose($file_count);
        list($today, $yesterday, $total, $date, $days) = split("%", $data);
        return $yesterday;
    }
    function total()
    {
        $file_count = fopen(APPLICATION_PATH."/../counter/count.txt", 'rb');
        $data = '';
        while (!feof($file_count)) $data .= fread($file_count, 4096);
        fclose($file_count);
        list($today, $yesterday, $total, $date, $days) = split("%", $data);
        echo $total;
    }
    function avg()
    {
        $file_count = fopen(APPLICATION_PATH."/../counter/count.txt", 'rb');
        $data = '';
        while (!feof($file_count)) $data .= fread($file_count, 4096);
        fclose($file_count);
        list($today, $yesterday, $total, $date, $days) = split("%", $data);
        echo ceil($total/$days);
    }  



?>

<?php
$page = new Default_Model_Page;
$menu = $page->menu(33);
?>
<div class="box">
    <div class="box-heading">Danh mục sản phẩm</div>
    <div class="box-content box-category">
        <ul id="custom_accordion"><?php
            foreach ($menu as $val) {
                $url = khongdau($val['title']);
                ?>
                <li><a href="<?= $this->baseUrl("/danh-muc/$url-$val[id].html") ?>" title="<?= $val['title'] ?>"><?= $val['title'] ?></a></li>
<?php } ?>
        </ul>
    </div>
</div>
<div class="box">
    <div class="box-heading">Sản phẩm khuyến mãi</div>
    <div class="box-content">
        <div class="box-product">
            <?php
            foreach ($page->list_Products_Nb(0,1) as $val) {
                $images = $val['images'];
                 $id = $val['id'];
                $mask = APPLICATION_PATH . "/../Upload/$images";
                if (file_exists($mask)) {
                    $images = $val['images'];
                } else {
                    $images = "no-img.png";
                }
                $url = khongdau($val['title']);
                $link= $this->baseUrl()."/chi-tiet/".$url."-".$id.".html";
                ?>
                <div>
                    <div class="image"><a href="<?= $link ?>"><img src="<?= $this->baseUrl("Upload/$images") ?>" alt="<?= $val['title'] ?>" /></a></div>
                    <div class="name"><a href="<?= $link ?>"><?= $val['title'] ?></a></div>
                    <div class="price"> <?= number_format($val['price'],0,".",".") ?> VNĐ</div>

                </div>
<?php } ?>
        </div>
    </div>
</div>
<!--Categories Part End-->
<!--Latest Product Start-->
<div class="box">
    <div class="box-heading">Sản phẩm mới</div>
    <div class="box-content">
        <div class="box-product">
            <?php
            foreach ($page->list_Products_Nb() as $val) {
                $images = $val['images'];
                 $id = $val['id'];
                $mask = APPLICATION_PATH . "/../Upload/$images";
                if (file_exists($mask)) {
                    $images = $val['images'];
                } else {
                    $images = "no-img.png";
                }
                $url = khongdau($val['title']);
                $link= $this->baseUrl()."/chi-tiet/".$url."-".$id.".html";
                ?>
                <div>
                    <div class="image"><a href="<?= $link ?>"><img src="<?= $this->baseUrl("Upload/$images") ?>" alt="<?= $val['title'] ?>" /></a></div>
                    <div class="name"><a href="<?= $link ?>"><?= $val['title'] ?></a></div>
                    <div class="price"> <?= number_format($val['price'],0,".",".") ?> VNĐ</div>

                </div>
<?php } ?>
        </div>
    </div>
</div>
<!--Latest Product End-->
<!--Specials Product Start-->
<div class="box">
    <div class="box-heading">Sản phẩm khác </div>
    <div class="box-content">
        <div class="box-product">
             <?php
            foreach ($page->list_Products_Nb(5) as $val) {
                $images = $val['images'];
                 $id = $val['id'];
                $mask = APPLICATION_PATH . "/../Upload/$images";
                if (file_exists($mask)) {
                    $images = $val['images'];
                } else {
                    $images = "no-img.png";
                }
                $url = khongdau($val['title']);
                $link= $this->baseUrl()."/chi-tiet/".$url."-".$id.".html";
                ?>
            <div>
                    <div class="image"><a href="<?= $link ?>"><img src="<?= $this->baseUrl("Upload/$images") ?>" alt="<?= $val['title'] ?>" /></a></div>
                    <div class="name"><a href="<?= $link ?>"><?= $val['title'] ?></a></div>
                    <div class="price"> <?= number_format($val['price'],0,".",".") ?> VNĐ</div>

                </div>
            <?php } ?>
        </div>
    </div>
</div>

<div class="box">
    <div class="box-heading">Lượt truy cập </div>
    <div class="box-content">
        <div class="box-product"><div class="Online">
            <div class="count">
                Tổng số truy cập: <b><?php total(); ?>  </b><br/>
                Online : <b><?php echo online(); ?> </b> 
            </div>
            
        </div>
        </div>
    </div>
</div>
<!--Specials Product End-->
