<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addcategory/">Thêm danh mục gốc</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listcategory/">Danh sách danh mục gốc</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addmenu/">Thêm menu</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listmenu//">Danh sách  menu</a><span class="divider">/</span>
        </li>
        
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addproducts/idmenu/0">Thêm sản phẩm</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listproducts//">Danh sách  sản phẩm</a>
        </li>
</ul>
</div>


<div class="row-fluid sortable">
<div class="box span12">
    <div class="box-header well" data-original-title>
        <h2><i class="icon-user"></i> Members</h2>
        <div class="box-icon">
                <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
        </div>
  </div>
     <div class="box-content">
 
<?php

foreach ($this->books as $val)
{
 $content = thay_the_fckeditor($val['content']);
   
 $id_category=$val['category_id'];
    ?>
   
  
 
    
<form action='' method='post' enctype='multipart/form-data' name='tt_mh' id='tt_mh'  class="form-horizontal">
    
    <div class="control-group">
        <label class="control-label" for="selectError">Chọn loại trang</label>
        <div class="controls">
          <select name="category_id" class="validate[required] text-input">
                      <option value="">------ Chọn danh mục ------</option>
            <?php 
            foreach($this->bookss as $val1)
            {
                
                $id1=$val1['id'];
                $title1=$val1['title'];
                 if ($id_category==$id1)
                 {$sl="Selected";} else {$sl="";}
               
	echo "<option value='$id1' $sl>";
				echo $title1;
			echo "</option>";
                        
            }
            ?>
                  </select>
        </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Tiêu đề </label>
                  <div class="controls">
                      <input name="title" value="<?php  echo $this->escape($val['title']); ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
    </div>
    
    <div class="control-group">
                  <label class="control-label" for="typeahead">Description </label>
                  <div class="controls">
                   
                     <textarea name="dis" cols="70" rows="10" class="span6 typeahead" id="typeahead" ><?php  echo $this->escape($val['dis']); ?></textarea>
               
                  </div>
	</div>
            
           
           
                     
                     
         <div class="control-group">
                  <label class="control-label" for="typeahead">Keywords </label>
                  <div class="controls">
                   
                     <textarea name="key" cols="70" rows="10" class="span6 typeahead" id="typeahead" ><?php  echo $this->escape($val['key']); ?></textarea>
               
                  </div>
	</div>
             
    <div class="control-group">
                  <label class="control-label" for="typeahead">Vị trí </label>
                  <div class="controls">
                    <input name="position" value="<?php  echo $val['position']; ?>" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" data-source='["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Dakota","North Carolina","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]'>
                    
               
                  </div>
	</div>
    
    <div class="control-group">
            <label class="control-label">Hiển thị</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="active" id="optionsRadios1" value="1" <?php if ($val['active']==1){    echo 'checked';} ?>>
                    Có
              </label>
              <div style="clear:both"></div>
              <label class="radio">
                    <input type="radio" name="active" id="optionsRadios2" value="2"<?php if ($val['active']==2){    echo 'checked';} ?>>
                   Không
              </label>
            </div>
	</div>
        <div class="control-group">
            <label class="control-label">Phân loại</label>
            <div class="controls">
              <label class="radio">
                    <input type="radio" name="thuocloai" id="optionsRadios1" value="1" <?php if ($val['thuocloai']==1){    echo 'checked';} ?>>
                    Chứa sản phẩm
              </label>
              <div style="clear:both"></div>
              <label class="radio">
                    <input type="radio" name="thuocloai" id="optionsRadios2" value="2"<?php if ($val['thuocloai']==2){    echo 'checked';} ?>>
                   Chứa nội dung
              </label>
            </div>
	</div>
    
          
            
               <div class="control-group" id="content">
              <label class="control-label" for="textarea2">Nội dung</label>
              <div class="controls">
                    <div id="div_vn_afc">
              <script type="text/javascript">
                    var oFCKeditor = new FCKeditor('content');
                    oFCKeditor.BasePath = "<?php echo $this->baseUrl(); ?>/fckeditor/";
                    oFCKeditor.Width	= 600 ;
                    oFCKeditor.Height	= 300 ;
                    oFCKeditor.Value="<?php echo $content; ?>";
                    oFCKeditor.Config["EnterMode"]		= "br" ;
                    oFCKeditor.Create();
                    document.getElementById('xEnter').value = "br" ;
                    //document.getElementById("noidung").value=jljl;
            </script>
            </div>
              </div>
	</div>
        <div class="form-actions">
                  <button type="submit" class="btn btn-primary">Save changes</button>
                  <button type="reset" class="btn">Cancel</button>
          </div>
    
      </form>
<?php
    }
?>
 </div></div></div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addcategory/">Thêm danh mục gốc</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listcategory/">Danh sách danh mục gốc</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addmenu/">Thêm menu</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listmenu//">Danh sách  menu</a><span class="divider">/</span>
        </li>
        
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addproducts/idmenu/0">Thêm sản phẩm</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listproducts//">Danh sách  sản phẩm</a>
        </li>
</ul>
</div>
