
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addcategory/">Thêm danh mục gốc</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listcategory/">Danh sách danh mục gốc</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addmenu/">Thêm menu</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listmenu//">Danh sách  menu</a><span class="divider">/</span>
        </li>
        
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addproducts/idmenu/0">Thêm sản phẩm</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listproducts//">Danh sách  sản phẩm</a>
        </li>
</ul>
</div>




<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">
        
        <form action="" method="post" enctype="multipart/form-data" name="tt_mh" id="tt_mh"  class="form-horizontal">
 <div class="control-group">
        <label class="control-label" for="selectError">Tìm kiếm</label>
        <div class="controls">
            <input name="title" type="text" class="span6 typeahead" id="typeahead"  data-provide="typeahead" data-items="4" style="float: left; margin-right: 10px; width: 250px" >
            
            
            <?php 
                echo "<select name=\"category_id\" id='category' class='form_tk' style=\"float: left;margin: 2px 10px 0px 0px\">";
                echo "<option value=\"\">";
				echo "------ Chọn danh mục gốc ------";
			echo "</option>";
            foreach($this->bookss as $val)
            {
                
                $id=$val['id'];
                $title=$val['title'];
               
	echo "<option value='$id' >";
				echo $title;
			echo "</option>";
            }
            ?>
	</select>
        <div id="div1" style="float: left; margin: 2px 10px 0px 0px">
                <select name="">
                    <option>--- Chọn menu ---</option>
                </select>
            </div>
            <div id="div2" style="float: left;margin: 2px 10px 0px 0px"></div>
            <button type="submit" class="btn btn-primary" style="margin-top: 2px">Search</button>
        </div>
    </div>
            

   
                 
               
   
</form>
 <script>
            $(document).ready(function(  ){
                $("select option:selected").each(function () {
                    $("div#div1").load("<?php echo $this->baseUrl(); ?>/admin/product/menu?id=" + $(this).val());
                });	
            });
	
            $("select#category").change(function () {
                var str = "";
                $("select option:selected").each(function () {
                    str += $(this).val() + " ";
                });
               // $("div#div2").text(str);
            })
            .change(function(  ){
                $("div#div1").load("<?php echo $this->baseUrl(); ?>/admin/product/menu?id=" + $(this).val());
            });
        </script>      




<table class="table table-striped table-bordered bootstrap-datatable datatable">
    <thead>
    <tr>
     <th >STT</th>
  
        <th >Tiêu đề</th>
        <th >Hình Ảnh</th>
    <th >Vị trí</th>
    <th >Hiển thị</th>
    <th >Thuộc menu</th>
    
     <th >Select</th>
    <th >Xóa</th>
    <th >Sửa</th>
    </thead>
  </tr>
  
  
  
      <?php
      $stt=1;
      $url=$this->baseUrl();
      foreach($this->books as $val)
        {
          
          $id=$val['id'];
          $menu_id=$val['menu_id'];
          
           
          $muser= new Admin_Model_Products();
       
           
          $edit=$this->url(array('action'=>'editproducts','id'=>$id, 'menu_id'=>$menu_id));
          $del=$this->url(array('action'=>'deleteproducts','id'=>$id));
          $update_active=$this->url(array('action'=>'useractive','id'=>$id,'active'=>0));
          $update_inactive=$this->url(array('action'=>'useractive','id'=>$id,'active'=>1));
          
            $status=$val['active'];
          if($status==1){$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" >Active</a>  <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\" style='display:none'>Inactive</a>";}
          else {$tt="<a href=\"javascript:void(0)\" id='active_$id' class=\"label label-success\" style='display:none' >Active</a> <a href=\"javascript:void(0)\" id='inactive_$id' class=\"label\">Inactive</a>";}
           
          
          
         
          ?>
      <tr id="row_<?= $id ?>">
      <td ><?php echo $stt;?></td>
   <?php  echo "<td align='center'>".$val['title']."</td>"; ?>

      <td> <img src="<?php echo $url;?>/Upload/<?php echo $val['images']; ?>" width="80" ></td>
    <td> <?php echo $val['position']; ?></td>
    <td id="demo_active_<?= $id ?>">  <?php echo $tt; ?> </td>
    <td><?php $muser->select_menu($menu_id); ?></td>
   
     <td><input type='checkbox'  ></td>
    <td>
    
        <a class="btn btn-danger"  id="row_del_<?= $id ?>" href='#' >
	<i class="icon-trash icon-white"></i> 
	Delete
	</a>
    
    
    </td>
    <td ><a class="btn btn-info" href="<?php echo $edit;?>">
	<i class="icon-edit icon-white"></i>  
	Edit                                            
	</a>
    </td>
  </tr>
  <script>
            $( "#row_del_<?= $id ?>" ).live('click',function(event_ref) {  event_ref.preventDefault();
           if (confirm('Are you sure you wish to delete this record?')){
                $.post('<?= $del ?>');
                $( "#row_<?= $id ?>" ).hide(2000);
          }
    });
    
     $( "#active_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_active ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='inactive_<?= $id ?>' class=\"label\">Inactive</a>" );
              
         
    });
    
    $( "#inactive_<?= $id ?>" ).live('click',function() {  
           
            $.post('<?= $update_inactive ?>');
               
               $( "#demo_active_<?= $id ?>" ).empty();
               $( "#demo_active_<?= $id ?>" ).append( "<a href=\"javascript:void(0)\" id='active_<?= $id ?>' class=\"label label-success\">Active</a>" );
          
    });
</script>
  <?php $stt++;} ?>
  
 
  <tr ><td colspan="9">
          
      <?php 
      if($stt>=15) {
      echo $this->paginationControl($this->books,  'Sliding', 'page/pagination.phtml');}
      else {}
      ?>     
      </td>
  </tr>
    
</table>
         
    </div> 
        
</div>
</div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addcategory/">Thêm danh mục gốc</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listcategory/">Danh sách danh mục gốc</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addmenu/">Thêm menu</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listmenu//">Danh sách  menu</a><span class="divider">/</span>
        </li>
        
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/addproducts/idmenu/0">Thêm sản phẩm</a> <span class="divider">/</span>
        </li>
         <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listproducts//">Danh sách  sản phẩm</a>
        </li>
</ul>
</div>

