<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/adddistrict/">Thêm khu vực</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listdistrict/">Danh sách khu vực</a> <span class="divider">/</span>
        </li>
         
</ul>
</div>




<div class="row-fluid sortable">
<div class="box span12">
    
    <div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Members</h2>
						<div class="box-icon">
							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
							<a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
							<a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
						</div>
  </div>
    <div class="box-content">
<table class="table table-striped table-bordered bootstrap-datatable datatable">
    <tr>
    <th >STT</th>
  
    <th>Khu vực</th>
    
     <th>Vị trí</th>
    <th >Xóa</th>
    <th >Sửa</th>
  </tr>
  
  
  
      <?php
      $stt=1;
      $url=$this->baseUrl();
      foreach($this->books as $val)
        {
          $id=$val['id'];
          $edit=$this->url(array('action'=>'editdistrict','id'=>$id));
          $del=$this->url(array('action'=>'deletedistrict','id'=>$id));
          
          ?>
      <tr>
      <td ><?php echo $stt;?></td>
   <?php  echo "<td align='center'>".$val['category']."</td>"; ?>

  
    <?php  echo "<td align='center'>".$val['position']."</td>"; ?>
    <td>
    
        <a class="btn btn-danger" href='<?php echo $del;?>' onclick="return confirm('Bạn có muốn xóa thông tin này?')">
	<i class="icon-trash icon-white"></i> 
	Delete
	</a>
    
    
    </td>
    <td ><a class="btn btn-info" href="<?php echo $edit;?>">
	<i class="icon-edit icon-white"></i>  
	Edit                                            
	</a>
    </td>
  </tr>
  
  <?php $stt++;} ?>
  
 
  <tr ><td colspan="8">
          
     <?php 
      if($stt>=15) {
      echo $this->paginationControl($this->books,  'Sliding', 'page/pagination.phtml');}
      else {}
      ?>  
      </td>
  </tr>
    
</table>
         
    </div> 
        
</div>
</div>
<div class="clear"></div>
<div>
<ul class="breadcrumb">
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/index/">Trang chủ</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/adddistrict/">Thêm khu vực</a> <span class="divider">/</span>
        </li>
        <li>
                <a href="<?php echo $this->baseUrl(); ?>/admin/product/listdistrict/">Danh sách khu vực</a> <span class="divider">/</span>
        </li>
         
</ul>
</div>

