

<div class="title"><a href="<?= $this->baseUrl() ?>">Trang chủ</a> » &nbsp; <a href="<?= $this->baseUrl("/video.html") ?>"><?php echo "Video"; ?></a></div>



    <div class="reservation_top">
        <div>          	 


           
                <div class="product-list list_video">
                    <?php
                    foreach ($this->list as $val) {
                       $title = $val["title"];
                       $url_1 = khongdau($title);
                       $video_id = $val["video_id"];
                        ?>
                       
                       
                            <div class="col-md-4 col-sm-4 col-xs-6 animation">
                                <div class="pgl-property">
                                    <div class="property-thumb-info">
                                        <div class="property-thumb-info-image">
                                            <a href="<?= $this->baseUrl("/videos/$url_1-$video_id.html") ?>">   
                                            <img src="http://img.youtube.com/vi/<?php echo get_youtube_id($val['link']); ?>/hqdefault.jpg" class="img-responsive"/>
                                            </a>

                                        </div>
                                        <div class="property-thumb-info-content">
                                            <h4><a href="<?= $this->baseUrl("/videos/$url_1-$video_id.html") ?>"><?= $title ?></a></h4>
                                         
                                        </div>

                                    </div>
                                </div>
                            </div>
      
                            

                            <?php
                        }
                    
                    ?>
                    <div class="clearfix"></div>
                </div>


        <div class="text-center">
            <?php
            echo "<div class=\"clearfix\"></div>  ";
            
            echo $this->paginationControl($this->list, 'Sliding', 'page/pagination_1.phtml');
            ?> 

        </div>
        <div class="clearfix"></div>

    </div>
</div>

